Algoritmo "programa 1"
// Disciplina   : Algoritmo de programação
// Professor   : Sérgio
// Descrição   : Média de notas
// Autor(a)    : Davi Mancini Ortolan
// Data atual  : 23/08/2025
Var
nota1, nota2, media: Real


Inicio
escreva ("Informe a nota 1: ")
leia (nota1)
escreva ("Informe a nota 2: ")
leia (nota2)
media <- (nota1 + nota2) / 2
escreval ("Sua média final é: ", media)



Fimalgoritmo