Algoritmo "programa 5"
// Disciplina   : Algoritmo de programação
// Professor   : Sérgio
// Descrição   : Volume do cilindro
// Autor(a)    : Davi Mancini Ortolan
// Data atual  : 23/08/2025
Const
pi <- 3.14
Var
altura, raio, volume: real


Inicio
escreva ("Altura: ")
leia (altura)
escreva ("Raio: ")
leia (raio)
volume <- pi * raio * raio * altura
escreva ("O volume é: ", volume)


Fimalgoritmo