Algoritmo "programa 13"
// Disciplina   : Algoritmo de programação
// Professor   : Sérgio
// Descrição   : Dólar e Real
// Autor(a)    : Davi Mancini Ortolan
// Data atual  : 24/08/2025
Const
R = 5.42

Var
D, valor_convertido: real


Inicio
escreva ("Quantos dólares você quer converter: ")
leia (D)
valor_convertido <- D*R
escreval (D," dólares equivale a", valor_convertido," reais")


Fimalgoritmo