Algoritmo "programa 3"
// Disciplina   : Algoritmo de programação
// Professor   : Sérgio
// Descrição   : Área do triângulo
// Autor(a)    : Davi Mancini Ortolan
// Data atual  : 23/08/2025
Var
base, altura, area: Real


Inicio
Escreva ("Digite a base do triângulo: ")
Leia (base)
Escreva ("Digite a altura do triângulo: ")
Leia (altura)
area <- (base*altura)/2
Escreva ("Área: ", area)


Fimalgoritmo