Algoritmo "programa 6"
// Disciplina   : Algoritmo de programação
// Professor   : Sérgio
// Descrição   : Área da circunferência
// Autor(a)    : Davi Mancini Ortolan
// Data atual  : 23/08/2025
Const
pi <- 3.1415
Var
raio, area: real


Inicio
escreva ("Qual o raio da circunferência? Escreva aqui: ")
leia (raio)
area <- pi * raio * raio
escreva ("Área circunferêcia: ", area)


Fimalgoritmo