Algoritmo "programa 9"
// Disciplina   : Algoritmo de programação
// Professor   : Sérgio
// Descrição   : Troca de valores das variáveis
// Autor(a)    : Davi Mancini Ortolan
// Data atual  : 23/08/2025
Var
x, y: inteiro


Inicio
escreva ("Valor de X: ")
leia (x)
escreva ("Valor de Y: ")
leia (y)
x <- x+y
y <- x-y
x <- x-y
escreval ("Valor final de X: ",x)
escreval ("Valor final de y: ",y)




Fimalgoritmo