Algoritmo "programa 7"
// Disciplina   : Algoritmo de programação
// Professor   : Sérgio
// Descrição   : área do cone
// Autor(a)    : Davi Mancini Ortolan
// Data atual  : 23/08/2025
Const
pi <- 3.1415
Var
raio, geratriz, area: real


Inicio
escreva ("raio: ")
leia (raio)
escreva ("geratriz: ")
leia (geratriz)
area <- pi * raio(raio + geratriz)
escreva ("Área cone: ", area)


Fimalgoritmo