Algoritmo "progama 2"
// Disciplina   : Algoritmo de programação
// Professor   : Sérgio
// Descrição   : Área de um retângulo
// Autor(a)    : Davi Mancini Ortolan
// Data atual  : 23/08/2025
Var
largura, comprimento, area: Real


Inicio
escreva ("Digite a largura do retângulo: ")
leia (largura)
escreva ("Digite o comprimento do retângulo: ")
leia (comprimento)
area <- largura*comprimento
escreva (area, " é a área do retângulo")


Fimalgoritmo